services:
  - docker

os:
  - Visual Studio 2017

build: off

environment:
  PYTHON: C:\Python36-x64

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%path%
  - pip install vcstool
  - pip install -U catkin_pkg EmPy pyparsing pyyaml
  - choco install -y gradle

build_script:
  - md \dev\ament\src
  - cd \dev\ament
  - curl -sk https://raw.githubusercontent.com/esteve/ament_java/master/ament_java.repos -o ament_java.repos
  - vcs import src < ament_java.repos
  - python src\ament\ament_tools\scripts\ament.py build --cmake-args -G "Visual Studio 15 2017 Win64" --
  - call install\local_setup.bat

  - md \dev\ros2\src
  - cd \dev\ros2
  - curl -sk https://raw.githubusercontent.com/esteve/ros2_java/%APPVEYOR_REPO_BRANCH%/ros2_java_desktop_travis.repos -o ros2_java_desktop_travis.repos
  - vcs import src < ros2_java_desktop_travis.repos
  - cd \dev\ros2\src\ros2_java
  - vcs custom --git --args checkout %APPVEYOR_REPO_BRANCH% || VER>NUL
  - cd \dev\ros2

  - ament build ^
    --parallel ^
    --skip-packages ^
    actionlib_msgs ^
    diagnostic_msgs ^
    geometry_msgs ^
    nav_msgs ^
    sensor_msgs ^
    shape_msgs ^
    stereo_msgs ^
    trajectory_msgs ^
    visualization_msgs ^
    --cmake-args ^
    -G "Visual Studio 15 2017 Win64" ^
    -DTHIRDPARTY=ON ^
    -DINSTALL_EXAMPLES=OFF ^
    -DCMAKE_FIND_ROOT_PATH="\dev\ament\install;\dev\ros2\install" ^
    --

after_build:
  - 7z a ros2_java.zip \dev\ros2\install
  - 7z rn ros2_java.zip install ros2_java\install
  - appveyor PushArtifact ros2_java.zip
