pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    xenial_android:
      ubuntu_distro: 'xenial'
      docker_tag: 'android'
      script_path: 'build_android.sh'
    xenial_java:
      ubuntu_distro: 'xenial'
      docker_tag: 'java'
      script_path: 'build_java.sh'
  maxParallel: 2

steps:
- script: |
    docker run -v $BUILD_SOURCESDIRECTORY/ci-scripts:/ci-scripts -e ROS2_JAVA_DIR=${AGENT_BUILDDIRECTORY}/ros2_java_build -e ROS2_JAVA_CI=1 -e ROS2_JAVA_BRANCH=${BUILD_SOURCEBRANCHNAME} -i --rm esteve/ros2-ubuntu-$UBUNTU_DISTRO-travisci:$DOCKER_TAG sh /ci-scripts/$SCRIPT_PATH
  displayName: 'Build for $(ubuntu_distro) / $(docker_tag)'
